#ifndef __TEXTURE_CONTAINERS_H__
#define __TEXTURE_CONTAINERS_H__

#include "types.h"
#include "model.h"

#define NUM_TEXTURE_CONTAINERS 27

typedef enum {
	ALIMBIC_TXTR = 0x0,
	TELEPORTER_TXTR = 0x1,
	ARTIFACT_TXTR = 0x2,
	ALIMBIC_EQUIP_TXTR = 0x3,
	ICE_EQUIP_TXTR = 0x4,
	LAVA_EQUIP_TXTR = 0x5,
	RUINS_EQUIP_TXTR = 0x6,
	GENERIC_EQUIP_TXTR = 0x7,
	PSYCHO_BIT_00_TXTR = 0x8,
	PSYCHO_BIT_01_TXTR = 0x9,
	PSYCHO_BIT_02_TXTR = 0xA,
	PSYCHO_BIT_03_TXTR = 0xB,
	PSYCHO_BIT_04_TXTR = 0xC,
	GUARD_BOT1_00_TXTR = 0xD,
	GUARD_BOT1_01_TXTR = 0xE,
	GUARD_BOT1_02_TXTR = 0xF,
	GUARD_BOT1_03_TXTR = 0x10,
	GUARD_BOT1_04_TXTR = 0x11,
	ALIMBIC_TURRET_00_TXTR = 0x12,
	ALIMBIC_TURRET_04_TXTR = 0x13,
	ALIMBIC_TURRET_05_TXTR = 0x14,
	LAVA_DAEMON_00_TXTR = 0x15,
	LAVA_DAEMON_03_TXTR = 0x16,
	BARBED_WAR_WASP_00_TXTR = 0x17,
	BARBED_WAR_WASP_02_TXTR = 0x18,
	BARBED_WAR_WASP_03_TXTR = 0x19,
	SECRET_SWITCH_TXTR = 0x1A,
} SHARED_TEXTURE;

extern const char* texture_container_names[NUM_TEXTURE_CONTAINERS];
extern CModel* texture_containers[NUM_TEXTURE_CONTAINERS];

void load_texture_container(CModel* model, SHARED_TEXTURE id);

#endif
